source 'https://rubygems.org'

# Or, run against the master branch
# (requires master-branch versions of all related RSpec libraries)
group :development, :test do
        %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
            gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'master'
        end
    end