interface Document : Node {
    readonly attribute Element? documentElement;

    HTMLCollection getElementsByTagName(DOMString qualifiedName);
    Element? getElementById(DOMString id);

    Element createElement(DOMString localName);
    Text createTextNode(DOMString data);
}
