interface Element : Node {
    undefined setAttribute(DOMString qualifiedName, DOMString value);

    HTMLCollection getElementsByTagName(DOMString qualifiedName);
    HTMLCollection getElementsByClassName(DOMString classNames);

    [Reflect] attribute DOMString id;
    [Reflect=class] attribute DOMString className;
    attribute DOMString innerHTML;
}
