/* https://html.spec.whatwg.org/multipage/webappapis.html#idl-definitions */

interface mixin GlobalEventHandlers {
    [IDLEventHandler] attribute EventHandler onclick;
    [IDLEventHandler] attribute EventHandler onload;
}
