interface HTMLInputElement : HTMLElement {
    /* [CEReactions] */ attribute /* [LegacyNullToEmptyString] */ DOMString value;

    attribute boolean checked;
    [Member] attribute boolean indeterminate;
};