interface MouseEvent : Event {
    [Member] readonly attribute double screenX;
    [Member] readonly attribute double screenY;
    [Member] readonly attribute double offsetX;
    [Member] readonly attribute double offsetY;
}