interface Window : EventTarget {
    readonly attribute WindowProxy window;
    readonly attribute WindowProxy self;
    readonly attribute WindowProxy frames;
    readonly attribute Document document;

    [Member] readonly attribute Navigator navigator;

    undefined alert(DOMString message);

    long setTimeout(Function handler, long timeOut);
    undefined clearTimeout(long id);
    long setInterval(Function handler, long timeOut);
    undefined clearInterval(long id);

    long requestAnimationFrame(Function callback);
    undefined clearAnimationFrame(long id);
}
